services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=it_doc
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
