export enum OrderStatus {
  IN_DIAGNOSTICS_QUEUE = 'IN_DIAGNOSTICS_QUEUE',
  REGISTERED = 'REGISTERED',
  DIAGNOSTIC = 'DIAGNOSTIC',
  DIAGNOSED = 'DIAGNOSED',
  APPROVED = 'APPROVED',
  APPROVED_AND_SPARE_PART_IS_ORDERED = 'APPROVED_AND_SPARE_PART_IS_ORDERED',
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
}

export enum Beneficiary {
  OOO = 'OOO',
  IP = 'IP',
}

export enum ClientType {
  PHYSICAL_PERSON = 'PHYSICAL_PERSON',
  LEGAL_PERSON = 'LEGAL_PERSON',
}

export enum Priority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
}
